# Generated by Django 5.1.3 on 2025-04-04 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="bus_schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bus_no", models.CharField(max_length=10)),
                ("route_id", models.CharField(max_length=10)),
                ("departure_place", models.CharField(max_length=10)),
                ("destination_place", models.CharField(max_length=50)),
                ("time", models.TimeField()),
            ],
        ),
    ]
