# Generated by Django 5.1.3 on 2025-04-04 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("busapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bus_schedule",
            old_name="time",
            new_name="start_time",
        ),
    ]
