# Generated by Django 5.1.3 on 2025-04-04 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("busapp", "0003_alter_bus_schedule_departure_place"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bus_schedule",
            name="departure_place",
            field=models.CharField(max_length=60),
        ),
        migrations.AlterField(
            model_name="bus_schedule",
            name="destination_place",
            field=models.CharField(max_length=60),
        ),
    ]
