# Generated by Django 4.0.3 on 2025-04-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0007_busschedule_alter_booking_bus'),
    ]

    operations = [
        migrations.AddField(
            model_name='busschedule',
            name='departure_time',
            field=models.TimeField(default='07:00'),
        ),
    ]
