# Generated by Django 4.0.3 on 2025-04-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0008_busschedule_departure_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bus_schedule',
        ),
        migrations.RemoveField(
            model_name='busschedule',
            name='departure_time',
        ),
        migrations.AddField(
            model_name='busschedule',
            name='departure_place',
            field=models.CharField(default='Arapalayam', max_length=60),
        ),
        migrations.AddField(
            model_name='busschedule',
            name='destination_place',
            field=models.CharField(default='Arapalayam', max_length=60),
        ),
        migrations.AddField(
            model_name='busschedule',
            name='route_id',
            field=models.CharField(default=1, max_length=10),
        ),
        migrations.AddField(
            model_name='busschedule',
            name='start_time',
            field=models.TimeField(default='07:00'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='busschedule',
            name='available_seats',
            field=models.IntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='busschedule',
            name='bus_no',
            field=models.CharField(max_length=10),
        ),
    ]
