# Generated by Django 4.0.3 on 2025-04-24 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('busapp', '0009_delete_bus_schedule_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='busschedule',
            name='current_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='busschedule',
            name='current_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='LocationUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='busapp.busschedule')),
            ],
        ),
    ]
